name: Daily SORN pull
on:
  branches: [ main ]
  schedule:
    - cron: "11 7 * * *"  # Arbitrary time outside continental US office hours
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to cloud.gov
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install cf cli
        uses: ./.github/cf-cli
      - name: Deploy to cloud.gov
        env:
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_ORG: ${{ secrets.CF_ORG }}
          CF_SPACE: ${{ secrets.CF_SPACE }}
          CF_CGHOSTNAME: test
        run: |
          ./.cloud-gov/deploy.sh update-sorn